"""认证域共享常量。"""

ROLE_ADMIN = "admin"
ROLE_EMPLOYEE = "employee"
USER_ROLES = (ROLE_ADMIN, ROLE_EMPLOYEE)

USER_STATUS_PENDING = "pending"
USER_STATUS_ACTIVE = "active"
USER_STATUS_DISABLED = "disabled"
USER_STATUSES = (
    USER_STATUS_PENDING,
    USER_STATUS_ACTIVE,
    USER_STATUS_DISABLED,
)

# 禁用的固定系统账号只承接认证改造前的历史数据；新记录必须显式绑定真实用户。
LEGACY_USER_ID = "00000000-0000-0000-0000-000000000000"
LEGACY_USERNAME = "__legacy_system__"

AUDIT_OUTCOME_SUCCESS = "success"
AUDIT_OUTCOME_FAILURE = "failure"
AUDIT_OUTCOME_DENIED = "denied"
AUDIT_OUTCOMES = (
    AUDIT_OUTCOME_SUCCESS,
    AUDIT_OUTCOME_FAILURE,
    AUDIT_OUTCOME_DENIED,
)
