#!/bin/sh
set -eu
# Passwords generated by init_microservices.py are URL-safe. Reject SQL metacharacters.
for value in "$IDENTITY_DB_PASSWORD" "$CHAT_DB_PASSWORD" "$KNOWLEDGE_DB_PASSWORD" "$IDENTITY_MIGRATION_PASSWORD" "$CHAT_MIGRATION_PASSWORD" "$KNOWLEDGE_MIGRATION_PASSWORD"; do
  case "$value" in *[!a-zA-Z0-9_-]*|'') echo 'Invalid database password format' >&2; exit 1;; esac
done
export MYSQL_PWD="$MYSQL_ROOT_PASSWORD"
mysql -uroot <<SQL
CREATE DATABASE IF NOT EXISTS identity_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS chat_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS knowledge_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS 'identity_app'@'%' IDENTIFIED BY '$IDENTITY_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'chat_app'@'%' IDENTIFIED BY '$CHAT_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'knowledge_app'@'%' IDENTIFIED BY '$KNOWLEDGE_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'identity_migration'@'%' IDENTIFIED BY '$IDENTITY_MIGRATION_PASSWORD';
CREATE USER IF NOT EXISTS 'chat_migration'@'%' IDENTIFIED BY '$CHAT_MIGRATION_PASSWORD';
CREATE USER IF NOT EXISTS 'knowledge_migration'@'%' IDENTIFIED BY '$KNOWLEDGE_MIGRATION_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON identity_db.* TO 'identity_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON chat_db.* TO 'chat_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON knowledge_db.* TO 'knowledge_app'@'%';
GRANT ALL PRIVILEGES ON identity_db.* TO 'identity_migration'@'%';
GRANT ALL PRIVILEGES ON chat_db.* TO 'chat_migration'@'%';
GRANT ALL PRIVILEGES ON knowledge_db.* TO 'knowledge_migration'@'%';
SQL
