"""Initial isolated domain schema. Frozen at migration creation."""
from alembic import op
import sqlalchemy as sa
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('durable_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_durable_tasks'))
    )
    op.create_index(op.f('ix_durable_tasks_status'), 'durable_tasks', ['status'], unique=False)
    op.create_table('maintenance_receipts',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('operation_id', name=op.f('pk_maintenance_receipts'))
    )
    op.create_table('agent_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('current_node', sa.String(length=64), server_default='queued', nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('turn_index > 0', name=op.f('ck_agent_runs_turn_index_positive')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], name=op.f('fk_agent_runs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('conversation_id', 'turn_index', name='uq_agent_runs_conversation_turn')
    )
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], name=op.f('fk_messages_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_messages')),
    sa.UniqueConstraint('run_id', 'role', name='uq_messages_run_role')
    )
    op.create_index(op.f('ix_messages_run_id'), 'messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('rating IN (-1, 1)', name=op.f('ck_user_feedback_rating_allowed')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], name=op.f('fk_user_feedback_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('pk_user_feedback'))
    )
    op.create_index(op.f('ix_user_feedback_run_id'), 'user_feedback', ['run_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrade is disabled; restore a verified backup instead.")
