"""Initial isolated domain schema. Frozen at migration creation."""
from alembic import op
import sqlalchemy as sa
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_heads',
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('active_snapshot', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document_heads'))
    )
    op.create_table('document_snapshots',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_document_snapshots'))
    )
    op.create_index(op.f('ix_document_snapshots_document_id'), 'document_snapshots', ['document_id'], unique=False)
    op.create_table('durable_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_durable_tasks'))
    )
    op.create_index(op.f('ix_durable_tasks_status'), 'durable_tasks', ['status'], unique=False)
    op.create_table('indexing_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('recreate', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('document_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('chunk_count >= 0', name=op.f('ck_indexing_jobs_chunk_count_non_negative')),
    sa.CheckConstraint('document_count >= 0', name=op.f('ck_indexing_jobs_document_count_non_negative')),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes >= 0', name=op.f('ck_indexing_jobs_file_size_bytes_non_negative')),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_indexing_jobs'))
    )
    op.create_index(op.f('ix_indexing_jobs_batch_id'), 'indexing_jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_status'), 'indexing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_created_by_user_id'), 'indexing_jobs', ['created_by_user_id'], unique=False)
    op.create_table('knowledge_audits',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_knowledge_audits'))
    )
    op.create_table('knowledge_state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('state_id', name=op.f('pk_knowledge_state'))
    )
    # ### end Alembic commands ###
    from app.config import get_settings
    op.execute(sa.text("INSERT INTO knowledge_state (state_id, collection, epoch) VALUES (1, :name, 0)").bindparams(name=get_settings().milvus_collection+"_ms_v1"))


def downgrade():
    raise RuntimeError("Destructive downgrade is disabled; restore a verified backup instead.")
